#!/bin/zsh

#####################################################
#                                                   #
# MAKE ALL BOOKS                                    #
#                                                   #
#####################################################

# What is this script making:
export PANDOC_ACTION='Book'

# Include the shared script:
. "${0:a:h:h}/includes/shared.zsh"

# Arguments passed to the scripts
arg=($(echo $*))

# Logging
start_log $0

process() {
    cd ${book:a:h:h}
    # Double check if it actualy a book or just a file with the same name
    if [ -f ./assets/make-book.md ]; then
        $local/terminal/make-book ${config[@]} $arg
    fi
}

find  $books -name make-book.md -type f | while read book; do process "$book"; done

# Logging
stop_log $0